swagger:"2.0"
info:
  version: "1.0.0"
  title: Desafio PontoTel
host: localhost:8000
basePath: /
schemes:
  -http
consumes:
  - application/json
produces:
  - application/json
paths:
  /search:
      post:
        description: Search the word in each url listed
        summary: Search
        operationId: GetOperations
        parameters:
          - name: urls
            description: List of urls to search the word
            in: body
            type: string[]
          - name: word
            description: Word to search in the specified urls
            in: body
            type: string[]
